"""Tests for the enhance_qml_code tool."""

import tempfile
from pathlib import Path

import pytest

from aurora_mcp.tools.qt.enhance_qml import enhance_qml_code


class TestEnhanceQMLTool:
    """Test cases for the enhance_qml_code tool."""

    def test_enhance_qml_with_marker(self):
        """Test enhancement of QML file with proper marker."""
        with tempfile.TemporaryDirectory() as temp_dir:
            # Create a QML file with enhancement marker
            qml_content = """// AURORA_MCP_ENHANCE_REQUIRED - Generated by figma_to_qml, run enhance_qml_code to improve
import QtQuick 2.0
import Sailfish.Silica 1.0

Page {
    objectName: "mainPage"

    PageHeader {
        title: qsTr("Test Page")
    }

    Rectangle {
        x: 20; y: 30
        width: 200; height: 100
        color: "blue"
    }
}"""

            qml_file = Path(temp_dir) / "TestPage.qml"
            with open(qml_file, "w") as f:
                f.write(qml_content)

            # Run enhancement
            result = enhance_qml_code(
                qml_file_path=str(qml_file), enhancement_types=["auto_layout"]
            )

            # Check result
            assert "✅ Enhancement completed!" in result
            assert "auto_layout" in result

            # Check file was modified
            with open(qml_file) as f:
                enhanced_content = f.read()

            assert "AURORA_MCP_ENHANCED" in enhanced_content
            assert "AURORA_MCP_ENHANCE_REQUIRED" not in enhanced_content

            # Check backup was created
            backup_file = qml_file.with_suffix(".qml.backup")
            assert backup_file.exists()

    def test_enhance_qml_without_marker(self):
        """Test enhancement fails without proper marker."""
        with tempfile.TemporaryDirectory() as temp_dir:
            # Create a QML file without enhancement marker
            qml_content = """import QtQuick 2.0
import Sailfish.Silica 1.0

Page {
    objectName: "mainPage"
}"""

            qml_file = Path(temp_dir) / "TestPage.qml"
            with open(qml_file, "w") as f:
                f.write(qml_content)

            # Run enhancement
            result = enhance_qml_code(qml_file_path=str(qml_file))

            # Check result
            assert "❌" in result
            assert "enhancement marker" in result

    def test_enhance_qml_file_not_found(self):
        """Test enhancement with non-existent file."""
        result = enhance_qml_code(qml_file_path="/non/existent/file.qml")

        assert "❌ QML file not found" in result

    def test_enhance_qml_multiple_types(self):
        """Test enhancement with multiple enhancement types."""
        with tempfile.TemporaryDirectory() as temp_dir:
            # Create a QML file with enhancement marker
            qml_content = """// AURORA_MCP_ENHANCE_REQUIRED - Generated by figma_to_qml, run enhance_qml_code to improve
import QtQuick 2.0
import Sailfish.Silica 1.0

Page {
    objectName: "mainPage"

    Rectangle {
        width: 200; height: 100
    }
}"""

            qml_file = Path(temp_dir) / "TestPage.qml"
            with open(qml_file, "w") as f:
                f.write(qml_content)

            # Run enhancement with multiple types
            result = enhance_qml_code(
                qml_file_path=str(qml_file),
                enhancement_types=["auto_layout", "components", "responsive"],
            )

            # Check result
            assert "✅ Enhancement completed!" in result

            # Check file was enhanced
            with open(qml_file) as f:
                enhanced_content = f.read()

            assert "AURORA_MCP_ENHANCED" in enhanced_content
            # Should contain evidence of enhancements
            assert "allowedOrientations" in enhanced_content  # responsive
            assert "objectName" in enhanced_content  # components

    def test_enhance_qml_with_figma_data(self):
        """Test enhancement with Figma metadata context."""
        with tempfile.TemporaryDirectory() as temp_dir:
            # Create Figma metadata file
            figma_data = {"name": "Test Design", "document": {"children": []}}

            figma_file = Path(temp_dir) / "figma-metadata.json"
            import json

            with open(figma_file, "w") as f:
                json.dump(figma_data, f)

            # Create QML file with enhancement marker
            qml_content = """// AURORA_MCP_ENHANCE_REQUIRED - Generated by figma_to_qml, run enhance_qml_code to improve
import QtQuick 2.0
import Sailfish.Silica 1.0

Page {
    objectName: "mainPage"
}"""

            qml_file = Path(temp_dir) / "TestPage.qml"
            with open(qml_file, "w") as f:
                f.write(qml_content)

            # Run enhancement with Figma data
            result = enhance_qml_code(
                qml_file_path=str(qml_file),
                figma_data_path=str(figma_file),
                enhancement_types=["auto_layout"],
            )

            # Check result
            assert "✅ Enhancement completed!" in result


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
