"""Tool for enhancing QML code generated from Figma with advanced features."""

import json
from pathlib import Path
from typing import Any


def enhance_qml_code(
    qml_file_path: str, enhancement_types: list[str] = None, figma_data_path: str = None
) -> str:
    """
    Enhance QML code generated from Figma with advanced Aurora OS features.

    This tool analyzes QML files marked with enhancement comments and improves them
    with auto-layout, components, effects, animations, and responsive design features.

    Args:
        qml_file_path: Path to QML file to enhance (must contain enhancement marker)
        enhancement_types: List of enhancement types to apply.
                          Options: ['auto_layout', 'components', 'effects', 'animations', 'responsive']
                          Default: ['auto_layout', 'components']
        figma_data_path: Optional path to Figma metadata JSON file for context

    Returns:
        Status report of enhancements applied

    Raises:
        Exception: If enhancement fails due to invalid inputs or processing errors
    """
    if enhancement_types is None:
        enhancement_types = ["auto_layout", "components"]

    try:
        # Validate input file
        qml_path = Path(qml_file_path)
        if not qml_path.exists():
            return f"❌ QML file not found: {qml_file_path}"

        # Read QML content
        with open(qml_path, encoding="utf-8") as f:
            qml_content = f.read()

        # Check for enhancement marker
        enhancement_marker = "// AURORA_MCP_ENHANCE_REQUIRED"
        if enhancement_marker not in qml_content:
            return "❌ File does not contain enhancement marker. Only files generated by figma_to_qml can be enhanced."

        # Read Figma data if provided
        figma_data = {}
        if figma_data_path and Path(figma_data_path).exists():
            with open(figma_data_path, encoding="utf-8") as f:
                figma_data = json.load(f)

        # Apply enhancements
        enhanced_content = qml_content
        applied_enhancements = []

        for enhancement_type in enhancement_types:
            print(f"🔄 Applying {enhancement_type} enhancement...")
            try:
                enhanced_content = _apply_enhancement(
                    enhanced_content, enhancement_type, figma_data
                )
                applied_enhancements.append(enhancement_type)
            except Exception as e:
                print(f"⚠️  Enhancement {enhancement_type} failed: {e}")
                continue

        # Remove enhancement marker and add completion marker
        enhanced_content = enhanced_content.replace(
            enhancement_marker,
            f"// AURORA_MCP_ENHANCED: {', '.join(applied_enhancements)}",
        )

        # Create backup of original
        backup_path = qml_path.with_suffix(".qml.backup")
        if not backup_path.exists():
            with open(backup_path, "w", encoding="utf-8") as f:
                f.write(qml_content)

        # Save enhanced content
        with open(qml_path, "w", encoding="utf-8") as f:
            f.write(enhanced_content)

        # Generate report
        report = _generate_enhancement_report(
            qml_file_path,
            applied_enhancements,
            len(qml_content.split("\n")),
            len(enhanced_content.split("\n")),
        )

        return f"✅ Enhancement completed!\n\n{report}"

    except Exception as e:
        error_message = f"❌ Enhancement failed: {str(e)}"
        print(error_message)
        return error_message


def _apply_enhancement(
    qml_content: str, enhancement_type: str, figma_data: dict[str, Any]
) -> str:
    """Apply specific enhancement type to QML content."""

    enhancement_strategies = {
        "auto_layout": _enhance_auto_layout,
        "components": _enhance_components,
        "effects": _enhance_effects,
        "animations": _enhance_animations,
        "responsive": _enhance_responsive,
    }

    enhancer = enhancement_strategies.get(enhancement_type)
    if not enhancer:
        raise ValueError(f"Unknown enhancement type: {enhancement_type}")

    return enhancer(qml_content, figma_data)


def _enhance_auto_layout(qml_content: str, figma_data: dict[str, Any]) -> str:
    """Enhance QML with proper layout components."""
    enhanced = qml_content

    # Add QtQuick.Layouts import if not present
    if "import QtQuick.Layouts" not in enhanced:
        lines = enhanced.split("\n")
        import_index = -1
        for i, line in enumerate(lines):
            if line.strip().startswith("import"):
                import_index = i

        if import_index >= 0:
            lines.insert(import_index + 1, "import QtQuick.Layouts 1.0")
            enhanced = "\n".join(lines)

    # Replace absolute positioning with layouts where possible
    # This is a simplified example - real implementation would parse QML AST
    enhanced = enhanced.replace(
        "x: 20; y: 30",
        "anchors.leftMargin: Theme.paddingLarge; anchors.topMargin: Theme.paddingLarge",
    )

    # Add layout spacing
    enhanced = enhanced.replace(
        "Column {", "Column {\n        spacing: Theme.paddingMedium"
    )

    enhanced = enhanced.replace("Row {", "Row {\n        spacing: Theme.paddingMedium")

    return enhanced


def _enhance_components(qml_content: str, figma_data: dict[str, Any]) -> str:
    """Extract reusable components from QML content."""
    enhanced = qml_content

    # Add objectName for debugging
    enhanced = enhanced.replace("Page {", 'Page {\n    objectName: "enhancedPage"')

    # Add property declarations for customization
    enhanced = enhanced.replace(
        "PageHeader {", 'PageHeader {\n        objectName: "pageHeader"'
    )

    return enhanced


def _enhance_effects(qml_content: str, figma_data: dict[str, Any]) -> str:
    """Add visual effects to QML content."""
    enhanced = qml_content

    # Add QtGraphicalEffects import if effects are needed
    if "Rectangle {" in enhanced and "import QtGraphicalEffects" not in enhanced:
        lines = enhanced.split("\n")
        import_index = -1
        for i, line in enumerate(lines):
            if line.strip().startswith("import"):
                import_index = i

        if import_index >= 0:
            lines.insert(import_index + 1, "import QtGraphicalEffects 1.0")
            enhanced = "\n".join(lines)

    return enhanced


def _enhance_animations(qml_content: str, figma_data: dict[str, Any]) -> str:
    """Add animations and transitions to QML content."""
    enhanced = qml_content

    # Add basic transitions to Page
    if "Page {" in enhanced and "transitions:" not in enhanced:
        enhanced = enhanced.replace(
            "Page {",
            """Page {

    transitions: [
        Transition {
            PropertyAnimation {
                duration: 300
                easing.type: Easing.InOutQuad
                properties: "opacity,scale"
            }
        }
    ]""",
        )

    return enhanced


def _enhance_responsive(qml_content: str, figma_data: dict[str, Any]) -> str:
    """Make QML content responsive for different screen sizes."""
    enhanced = qml_content

    # Add orientation support
    if "allowedOrientations:" not in enhanced:
        enhanced = enhanced.replace(
            "Page {", "Page {\n    allowedOrientations: Orientation.All"
        )

    # Replace fixed sizes with responsive ones
    enhanced = enhanced.replace(
        "width: parent.width",
        "width: Math.min(600, parent.width - 2 * Theme.paddingLarge)",
    )

    return enhanced


def _generate_enhancement_report(
    file_path: str,
    applied_enhancements: list[str],
    original_lines: int,
    enhanced_lines: int,
) -> str:
    """Generate enhancement report."""
    return f"""# QML Enhancement Report

## File Enhanced
- **Path**: `{file_path}`
- **Original Lines**: {original_lines}
- **Enhanced Lines**: {enhanced_lines}
- **Lines Added**: {enhanced_lines - original_lines}

## Applied Enhancements
{chr(10).join(f"- ✅ **{enhancement}**: Applied successfully" for enhancement in applied_enhancements)}

## Backup
- Original file backed up as `{Path(file_path).with_suffix(".qml.backup")}`

## Next Steps
1. **Test Enhanced Code**: Build and test the enhanced QML
2. **Fine-tune**: Adjust spacing, colors, and animations as needed
3. **Add Business Logic**: Implement functionality and data binding
4. **Review Components**: Extract additional reusable components if needed

---
🤖 Enhanced with Aurora MCP enhance_qml_code tool"""


__all__ = ["enhance_qml_code"]
